"""empty message

Revision ID: 048194287a57
Revises: 15b7e9794b21
Create Date: 2023-11-15 00:53:24.927716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048194287a57'
down_revision = '15b7e9794b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('preview_image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_image_url', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
