carts_data = [
    
  {"user_id": 3, "transaction_complete": True},
  {"user_id": 3, "transaction_complete": True},
  {"user_id": 3, "transaction_complete": True},
  {"user_id": 3, "transaction_complete": True},
  {"user_id": 2, "transaction_complete": False},
  {"user_id": 3, "transaction_complete": True},
  {"user_id": 1, "transaction_complete": True},
  {"user_id": 3, "transaction_complete": True},
  {"user_id": 2, "transaction_complete": True},
  {"user_id": 2, "transaction_complete": True},
  {"user_id": 2, "transaction_complete": True},
  {"user_id": 3, "transaction_complete": True},
  {"user_id": 2, "transaction_complete": True},
  {"user_id": 3, "transaction_complete": True},
  {"user_id": 2, "transaction_complete": True},
  {"user_id": 3, "transaction_complete": True},
  {"user_id": 1, "transaction_complete": False},
  {"user_id": 2, "transaction_complete": True},
  {"user_id": 1, "transaction_complete": True},
  {"user_id": 1, "transaction_complete": True},
  {"user_id": 1, "transaction_complete": True},
  {"user_id": 3, "transaction_complete": False},
  {"user_id": 2, "transaction_complete": True},
  {"user_id": 2, "transaction_complete": True},
  {"user_id": 1, "transaction_complete": True},
  {"user_id": 2, "transaction_complete": True},
  {"user_id": 1, "transaction_complete": True},
  {"user_id": 2, "transaction_complete": True},
  {"user_id": 3, "transaction_complete": True},
  {"user_id": 2, "transaction_complete": True},
  {"user_id": 1, "transaction_complete": True},
    
]